# Generated by Django 5.1.7 on 2025-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(
                default="default/default.jpg", upload_to="news_images/"
            ),
        ),
    ]
