# Generated by Django 5.1.7 on 2025-03-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="sponsor_logos/")),
                ("image", models.ImageField(upload_to="sponsor_images/")),
                ("is_active", models.BooleanField()),
            ],
        ),
    ]
