# Generated by Django 5.1.7 on 2025-03-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_sponsor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsor",
            name="logo",
        ),
    ]
